### ISSUE TITLE
Agency Caseworker is unable to login after approval

### ISSUE THREAD

**Issue by lsoman** [on-site/grantzilla#226]
Issue:
Agency Caseworker is unable to login even after approval
Eg: Caseworker for Goodwill is approved but when trying to login get the following error

![image](https://cloud.githubusercontent.com/assets/15737859/13058431/1bf5f48e-d3d8-11e5-94a8-c5838efd960d.png)

Steps to duplicate:
-Register caseworker with Goodwill
-Administrator approves the caseworker
-When caseworker try to login. He is asked to verify the email
-There was no email received by the caseworker

**Comment by betesh** [comment]
This is because of DNS issues between HIF's DNS provider and the email delivery service we are using (Mailgun).  All attempts to send email are being blocked by Mailgun because the SPF records sent to the DNS provider have not propogated.  The only way to resolve this is to have an HIF representative call the DNS provider to follow up on this issue.
