### ISSUE TITLE
Can not change password in the user profile

### ISSUE THREAD

**Issue by mbatraski** [on-site/grantzilla#63]
When changing password, get an error message:

We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

**Comment by betesh** [comment]
This is because email isn't working.

Email isn't working for 2 reasons:
1) DNS for mailgun has not been fully set up yet (something wrong on the DNS provider's end.  We need to get on the phone with them and HIF to debug) (#114 will mitigate this by making devise send emails in a background process.  So the error won't occur within the web app anymore)
2) https://github.com/on-site/grantzilla/pull/47/files#r51004252 (which is fixed by #108)

**Comment by joseph-ravenwolfe** [comment]
I am unable to verify this issue. Closing for now. Please reopen if this is repeatable.
